version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.26

    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db: