spring:
  #h2:
    #console.enabled: true
  #datasource:
    #url: jdbc:h2:mem:mysqldb
  datasource:
    url: jdbc:mysql://localhost:3306/school_db?useSSL=false
    username: masterjedi
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

