CREATE SCHEMA IF NOT EXISTS testdb AUTHORIZATION sa;

CREATE TABLE STUDENT (
    ID BIGINT auto_increment,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(255),
    CREATED_AT TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE COURSE (
    ID BIGINT auto_increment,
    DESCRIPTION VARCHAR(255),
    MNEMONIC VARCHAR(50),
    CREATED_AT TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE STUDENT_COURSE(
    STUDENT_ID BIGINT NOT NULL,
    COURSE_ID BIGINT NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID)
);

INSERT INTO STUDENT VALUES (1, 'Anish', 'Visrolia', 'anish.visrolia@metadata.io', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO STUDENT VALUES (2, 'Emily', 'Hoang', 'emily.hoang@metadata.io', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO STUDENT VALUES (3, 'Jaime', 'Rojas', 'jaime.rojas@metadata.io', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO STUDENT VALUES (4, 'Francisco', 'Martin', 'francisco.martin@metadata.io', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO STUDENT VALUES (5, 'Ernesto', 'Acosta', 'ernestox09@gmail.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO COURSE VALUES (1, 'CSS 101', 'CSS101', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO COURSE VALUES (2, 'Class 1', 'CL101', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO COURSE VALUES (3, 'Class 2', 'CL201', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO COURSE VALUES (4, 'Class 3', 'CL301', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO COURSE VALUES (5, 'Class 4', 'CL401', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO COURSE VALUES (6, 'Class 5', 'CL501', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO COURSE VALUES (7, 'Class 6', 'CL601', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO COURSE VALUES (8, 'Class 7', 'CL701', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO COURSE VALUES (9, 'Class 8', 'CL801', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO STUDENT_COURSE VALUES (1, 2);
INSERT INTO STUDENT_COURSE VALUES (2, 3);
INSERT INTO STUDENT_COURSE VALUES (3, 1);
INSERT INTO STUDENT_COURSE VALUES (4, 4);